### ISSUE TITLE
Adding new deprecation schedule to BioSTEAM

### ISSUE THREAD

**Issue by yoelcortes** [dstew16/Biorefinery-Tax-Incentives#1]
Here is how to do it:

```python
import numpy as np
from biosteam._tea import _MACRS
_MACRS['Name'] = np.array([0.5, 0.2, 0.1, 0.1, 0.1])
```

Hope this helps!

**Comment by dstew16** [comment]
I have been looking into the incentive related to this new depreciation schedule, and frankly, I still don't know exactly how it's meant to be implemented. I would like to discuss with you tomorrow the text of the actual law that establishes this incentive to see if we can figure it out together. Depending on how that goes, we can consider skipping this or adding it in later.

**Comment by yoelcortes** [comment]
sounds good!

**Comment by dstew16** [comment]
I just want to check in on the status of including this depreciation schedule and incentive. The last thing I remember is that you said you had an idea for how to implement it, but we can discuss it again.

Basically I think we just need to include a new depreciation schedule like the one in the first post of this chain but we were also going to have to avoid double counting something, but I forget what it was now.

We can discuss more! Let me know if you remember what you had in mind!
