### ISSUE TITLE
Problem with using IncentivesTEA

### ISSUE THREAD

**Issue by dstew16** [dstew16/Biorefinery-Tax-Incentives#4]
I've been getting some strange results when using the new `IncentivesTEA`. From what I can tell, the `tax_incentives.py` and `incentives_tea.py` files are working properly, so I think the problem is occurring when I use the `IncentivesTEA` with BioSTEAM's Monte Carlo analysis features in my `IncentivesAnalysis.py` file.

You can see the setup in that file, but I've created a `solve_MFSP_with_inc_X()` metric function for each incentive. I've noticed that after running some Monte Carlo simulations, incentives 1, 2, 3, 4, 6, 7, 8, 17, and 22 yield exactly the same MFSP. I can't find any commonality between all 9 of these incentives, though 5 of them are exemptions related to property tax, so I'm not sure what's causing this issue. I'm thinking maybe I need to 'reset' the value of the incentives within each function, similar to how the ethanol price is set to 0? Also, incentive 8 depends on utility tax, which we currently don't consider in the TEA. The fact that 8 other incentives are returning the same value as a quasi-nonfunctional incentive is concerning.

To try and figure this out, I created the `get_incentives_amt_X()` metric functions starting on line 201 to see the value of the incentives being returned. For one thing, I noticed that no matter which incentive number you specify, the only type of incentive that is populated is the `tea.refunds`, so I'm not sure what's going on with that. I also checked several of the 9 incentives listed above, and I found that they all generated the same value for `tea.refunds`, which is problematic because 1) they are not all refunds and 2) there is no way they should be worth the exact same amount.

If you could help me get to the bottom of this, that would be great. Like I said, I think it has something to do with using the `IncentivesTEA` with the Monte Carlo analysis. Thanks!

**Comment by yoelcortes** [comment]
Fixed! The metrics are run in the order you give it. Changing the incentive_numbers doesn't actually run the TEA, so only the data from the last TEA (incentive 23 I think) was being used. I just reordered the metrics to fix this up (and simplified the code). I also fixed some other bugs in the TEA class (like including the fuel tax).

By the way, here is a helpful hint: to check for general results for a given incentive, use something like `table['Incentives 2']` to get a data frame of the given incentive number (2 in the example).

I think the next step is to run the analysis and plot it. Then we can look at any problems with each incentive. 

Hope this helps!

**Comment by dstew16** [comment]
Thank you! I know we briefly discussed the importance of the order of the metrics but I wasn't sure what the proper order would be. I also wasn't sure how to set up a single metric function to return the value of all incentives, but I see the setup now.  Unfortunately, I get errors when I try to run the new files. The errors occur when I use the `incentives_analysis.py` file but I think they extend to other files.

The first one that comes up also occurred when I used a previous version of the `incentives_tea.py` file, but I figured out a workaround with #. The error message is:

runfile('/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/incentives/incentives_analysis.py', wdir='/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/incentives')
  File "<fstring>", line 1
    (IRR_without_incentives=)
                           ^
SyntaxError: invalid syntax

Which seems to refer to line 162 in `incentives_tea.py` (although the red error marker (!) shows up at line 1. This is the same error message I got previously, but I muted it by #ing out lines 146-163. I'm not sure if this is ok because I'm not sure if these lines were just used for testing or are important to the function of the TEA. If you could help me clarify that, that would be great.

After I #ed out lines 146-163 and ran the `incentives_analysis.py` file again, I got the following error:

  File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/incentives/incentives_analysis.py", line 28, in <module>
    model = bst.Model(lc.lipidcane_sys)

TypeError: __init__() missing 1 required positional argument: 'metrics'

So it seems to dislike that we defined the model before the metrics. Maybe I'm using an outdated version of BioSTEAM? I'll try updating and tweaking things and see if that helps.

I think the second error message will be simple enough for me to fix, but it would be great if you could help me clarify what's going on with the first error message. Thanks!

**Comment by dstew16** [comment]
Quick update: I updated BioSTEAM and I no longer get the error message related to the model/metrics.

After running `incentives_analysis.py` again, however, incentives 1, 2, 3, 4, 6, 7, 8, 17,  and 22 still yield the same MFSP, and the `get_exemptions`, etc metrics show a value of 0 for all incentives. Ignoring incentives 8 and 21 for now since we expect them not to work / yield 0, I looked back through all the variables for all the incentives and found one commonality between the 8 incentives that don't work: they use the `construction_flow` function. The 13 incentives that seem to be working do not use this function, they use the `yearly_flows` function.

At first glance, nothing jumps out as being wrong with the `construction_flow` function, but it seems like this would be a good place to start figuring out what's up with these 8 incentives.

**Comment by yoelcortes** [comment]
Cool, just fixed two bugs that led to this problem:
* We now use cumulative sum (instead of yearly cash flow) for property value of equipment.
* Sales tax is taken into account during construction years (when equipment is purchased).

Let me know if you find any more oddities,
Thanks!

**Comment by dstew16** [comment]
This fix seems to have worked, or at least we're no longer getting all 0 values for these incentives. However, I noticed that the `construction_flows` function will only fill in an array at locations [:start], whereas all of my incentives functions fill in arrays and depend on other array values from [start:start+duration]. I'm just wondering if we're setting ourselves up to get strange/inaccurate results because we've defined these functions to fill in exactly opposite locations?

Also, I think some of these parameters would make more sense to use the `yearly_flows` function rather than `construction_flows`. For example, wouldn't there be a property taxable value to determine property tax for every year of biorefinery operation, not just until the start year?

Maybe I'm just misunderstanding the code setup. Let me know your thoughts!

**Comment by yoelcortes** [comment]
Hi Dalton, yes! `contruction_flows` will only fill the array in every year before the start of the venture. This is because capital costs are incurred before the plant can start producing (when units are purchased). But note that for property_value, biodiesel_eq, and ethanol_eq (among others), we are taking the cumulative some of the cashflows to get the total value of the equipment and passing that to the `determine_incentives` function. I think you may have missed the ".cumsum()" at the end of the lines that define some variables...

I've been looking at your commits lately, looking good! I'll review them in more detail before our next meeting.

Thanks!

**Comment by dstew16** [comment]
I did see the .cusum() but I just misunderstood what it was summing haha. Your explanation makes sense, I think we're good to go!
