### ISSUE TITLE
State scenarios analysis

### ISSUE THREAD

**Issue by dstew16** [dstew16/Biorefinery-Tax-Incentives#5]
A big part of the publication we are working towards will be a comparison of MFSP after considering state-specific scenarios for TEA. I've started working on this with the `state_scenarios_analysis.py` file, but I'm having trouble generating results. 

I think the problem starts at line 71. What I want to happen is: for a given biorefinery simulation, perform a TEA for all 50 states using the combination of parameters specified in the `state_scenarios_for_import.xlsx` file with the MFSP as the output (so 50 MFSPs total). Then repeat this some number of times using Monte Carlo analysis to get a distribution of results under uncertainty. This is similar to what we did to analyze the effects of each of the tax incentives previously, but I think there is an issue with changing the TEA parameters within the for loop. Specifically, I think the way I'm trying to pass the `incentive_numbers` parameter might be problematic.

Could you help me figure out how to restructure this analysis? Thank you!

**Comment by yoelcortes** [comment]
Sorry for the late response! I'll look into this within the next few days

**Comment by dstew16** [comment]
No problem, and thank you! I meant to email you about this as well but forgot.

I don't it will be too difficult to solve the issue, it's just difficult for me to pinpoint exactly where the problem is because it doesn't output an error message, my output table is just full of 0s. I will keep trying to fix it too.

**Comment by yoelcortes** [comment]
I believe it should work now. It was a minor bug where a tuple of incentives were given but only one incentive number was expected, now the "MFSP_getter" and "MFSP_reduction_getter" functions expect a many incentives (e.g. tuple[int] or list[int]). You might have to update biosteam to the latest version. The new version made the operating_hours property of TEA objects public (from '_operating_hours' to 'operating_hours').

Thanks!

**Comment by dstew16** [comment]
Got it, thank you! I'm planning to share some of these results soon-ish, but there are also a couple of other issues I want to discuss with you, so I'll be reaching out again.
