### ISSUE TITLE
Make IncentivesTEA functional with cornstover and sugarcane biorefineries

### ISSUE THREAD

**Issue by dstew16** [dstew16/Biorefinery-Tax-Incentives#6]
For the manuscript, we've decided to evaluate cornstover and sugarcane biorefineries since they're more established feedstocks than lipidcane. However, the IncentivesTEA class is currently slightly incompatible with these biorefineries.

I believe the only issue arises when specifying the `ethanol_production_sys` for the TEA class. The two biorefineries currently don't have this attribute. I tried looking through the system files and setting this attribute as the fermentation system (`R301`?), but then I get an error something like: 'seed train has no cost attribute', when I try to run the TEA, and I don't know how to address that.

I created the `cs_eval.py` and `sc_eval.py` files to evaluate these two biorefineries. If you scroll through to somewhere around line 106, you can see where I was implementing the approach I just described above. The simplest fix might be to give these two biorefineries the `ethanol_production_sys` attribute that you gave the lipidcane biorefinery. Please let me know if you think this is a good approach and can implement it, and if there is anything you want me to take care of.

Thank you!

**Comment by dstew16** [comment]
Actually, more accurately, the TEA attribute is `.ethanol_group` and we set it as the `.ethanol_production_units` for the lipidcane biorefinery.

This attribute shows up at line 106 in `cs_eval.py` and line 61 in `sc_eval.py`.

Thanks!

**Comment by yoelcortes** [comment]
Hi Dalton,

It's a very good attempt, I'd be happy to fix up the code. I'd like to note a couple of things you might not be aware of:
* The conventional ethanol and cellulosic ethanol TEA objects are very different. For example, the cellulosic TEA object differentiates between inside and outside-boundary limits unit operations, uses financing, and uses bare-module factors (instead of a Lang factor), among other differences. To better compare between cellulosic and coventional, I'll use the "cellulosic ethanol production TEA" method for both.
* `ethanol_production_units` must be biosteam.UnitGroup object, which can be created from a list of units. Because the biorefinery only produces ethanol, pretty much all unit operations will be included in this group, except for facilities and storage tanks. 

I'll take care of implementing the new TEA objects (using the cellulosic ethanol production TEA as the parent class), and making sure your "eval" files work. I should be done by the weekend, I'll let you know as soon as I am!

Thanks!

**Comment by yoelcortes** [comment]
Hi Dalton,

The code should be working now. I believe you'll need the latest version of biosteam and biorefineries from github. I removed the cs_eval.py and sc_eval.py modules in favor of one model.py module that can create the Model object given the name of the biorefinery.

Each biorefinery TEA uses the methods and assumptions from the original published design. Let me know if there is anything else I can help with.

Thanks!

**Comment by dstew16** [comment]
Thanks Yoel!!

I had actually pulled your updates a few days ago, ran into errors, and was about to contact you when I noticed you had pushed more updates and still seemed to be working. Thanks for letting me know you're finished!

I'll pull all the latest versions and let you know how it goes!

Dalton

**Comment by dstew16** [comment]
Hi Yoel,

The integration with the new biorefineries seems to be overall functional, but I'm getting some strange TEA results when I simulate the cornstover biorefinery that don't occur with the sugarcane or corn biorfineries. I haven't pinpointed the cause of the issue yet, but I did notice that the cornstover biorefinery is the only one of the three that utilizes the `CellulosicIncentivesTEA` class (the other two use a `ConventionalIncentivesTEA`), so that seems like a reasonable place to start our debugging.

By strange results, I mean that sometimes the monetary value of the tax incentives turns negative, and then the TEA subtracts that negative value, resulting in an incentivized MESP that is higher than the baseline MESP (which should never happen). Anecdotally, I've noticed that this problem only seems to be occurring for tax incentives with relatively low values - not sure if that's a clue or not. You can see the results I'm referencing in the `MESPs_all_params.xlsx` spreadsheet I attached. The highlighted columns (LF, LL, MA, MD, etc.) show which incentives are outputting negative incentive values and MESP reductions that are actually additions. I believe incentives 11, 12, 15, and 19 are the weird ones. I can't find any commonalities between these incentives other than they may be related to sales tax and/or some equipment costs, which in turn depend on the Lang factor for the `CellulosicTEA`.

The `cs_results.xlsx` sheet also shows some weird results in columns BM, BR, and BZ. This sheet is the result
of a state specific analysis, and the incentivized MESPs in some states (Alabama, Louisiana, and Virginia) were higher than the baseline MESPs. The incentives available in these states are 8, 9, 15, and 19. Again, no real commonalities between these incentives, but I do know that incentives 15 and 19 tend to be low value. Incentive 11 was not included in this analysis, but incentive 12 was included for for Iowa (column BO) and seemed to work properly this time.

I hope I'm not providing too much information for what could be a simple bug, but I happened to take a look at a cashflow table for one cornstover biorefinery simulation where incentive 23 was included, and I noticed that the Incentives column (column M in `problematic_cashflow?.csv` included some negative values, which shouldn't happen as far as I know. Is there a reason this might occur that I'm unaware of?

I hope my description of this issue makes enough sense for you to start looking into. If I didn't describe anything well enough, or you need more information, please let me know. Thank you!

[MESPs_all_params.xlsx](https://github.com/dstew16/Biorefinery-Tax-Incentives/files/6811701/MESPs_all_params.xlsx)
[cs_results.xlsx](https://github.com/dstew16/Biorefinery-Tax-Incentives/files/6811785/cs_results.xlsx)
[problematic_cashflow?.csv](https://github.com/dstew16/Biorefinery-Tax-Incentives/files/6811805/problematic_cashflow.csv)

**Comment by yoelcortes** [comment]
Hi Dalton,

Thanks for the detailed description on the bug, it helped a ton! It should be fixed now. I believe the issue was that when we assess income taxes, some taxable cash flows were negative. I just made the negative values zero before we compute income taxes.

Let me know if you find any other issues!
Thanks,

**Comment by dstew16** [comment]
Hi Yoel,

I think there is just one more small issue with the TEA now, it's taken me awhile to find.

I've noticed that there are two tax incentives (incentives 3 and 4) that always have a monetary value of 0, which shouldn't happen. These two incentives depend on the value of biodiesel and ethanol producing equipment, respectively. In the `incentives_TEA` file, these values are calculated in lines 135, 137, 143, and 145 using the `.get_purchase_cost()` and `.get_installed_cost()` methods. However, I've noticed that these methods always return 0. This problem with calculating purchase and installed costs only seems to be happening in these lines, not the overall TEA. I've had trouble tracking down the definitions of these methods to see how they work, so I'm not sure how to resolve this.

If you could track these methods down and make sure they're functioning properly, i.e. not returning a $0 cost for the biorefinery's equipment, I would really appreciate it. Let me know if you need anymore info from me.

Thank you!

**Comment by dstew16** [comment]
Thanks Yoel!

I know incentive 3 will only have a value for biorefineries that produce biodiesel, but I thought it was also being affected by the methods. Regardless, it seems to be working properly for incentive 4 now.

From what I can tell this is one of the last issues with the code! Getting closer to that publication! :)
